### ISSUE TITLE
The widget does not work with the 0.3.3 version of htmlwidgets framework

### ISSUE THREAD

**Issue by armish** [armish/coffeewheel#2]
Here is the latest change in `htmlwidgets` that causes the problem:
https://github.com/ramnathv/htmlwidgets/pull/28
https://github.com/ramnathv/htmlwidgets/issues/101

here is some more information kindly provided by @happyshows:
https://github.com/armish/coffeewheel/issues/1#issuecomment-97560514

The current coffeewheel is compatible with `htmlwidgets` versions `>= 0.2.2` and `<= 0.3.2`.

**Comment by happyshows** [comment]
More information, I encountered the following error msg when I migrate to 0.3.3

Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.

**Comment by happyshows** [comment]
@armish I have updated htmlwidgets to 0.4.0 and the problem seems to go away.
Hence I'm closing this issue.

**Comment by armish** [comment]
Thanks for following up on this @happyshows -- closing the issue as you suggested.
