### ISSUE TITLE
Change Police/font size

### ISSUE THREAD

**Issue by kmezhoud** [armish/coffeewheel#3]
Dear Dr Arman,
I am interesting to use coffeewheel package. Can I set the font size or the police?
Thanks
Karim

**Comment by armish** [comment]
Hi Karim,

Thanks for reaching out and as for your question: yes, you can definitely set the style. Currently the text style is set to browser's default. You should be able to override these settings by targeting `text` elements within your container division via CSS rules.

Unfortunately, the current implementation does not allow you to directly set the font style/size.

Hope this helps.

**Comment by kmezhoud** [comment]
Thanks,
And where is the CSS rules?
I would like to use it in Shiny app. Maybe it will be possible to set the font through css file?
Karim

**Comment by armish** [comment]
This page has some information on how to include custom CSS in Shiny Apps:
http://shiny.rstudio.com/articles/css.html

**Comment by kmezhoud** [comment]
Thanks
