### ISSUE TITLE
Legend for colors

### ISSUE THREAD

**Issue by kmezhoud** [armish/coffeewheel#4]
Hi,
Is there a way to add a legend for colors?
Thanks

**Comment by armish** [comment]
Hi Karim,

Unfortunately no -- you have to create multiple plots to accomplish that and label the colors you use. We have a fork of this project that was used in one of our research project and it supports legends for gradient-based color schemes: https://github.com/armish/metabologram

Please feel free to use that if that better suits your need.

Thanks,
-- Arman

**Comment by kmezhoud** [comment]
Ok,
Thanks
