### ISSUE TITLE
ShinyApp

### ISSUE THREAD

**Issue by kmezhoud** [armish/coffeewheel#5]
Hi Arman,
There is missing something to get coffeewheel in mainPage. Could you correct me? Thanks

shinyApp(

  shinyUI(fluidPage(

  mainPanel(
    plotOutput('getCoffeewheel')
  )
)),

shinyServer(function(input, output, session){

 output$getCoffeewheel <- renderPlot({
   coffeewheel(sampleWheelData, width=500, height=500, main="Sample Wheel Title", partitionAttribute="value")
 })

})
)

**Comment by kmezhoud** [comment]
Error in instance$elementId : $ operator is invalid for atomic vectors

shinyApp(
  shinyUI(fluidPage(
  mainPanel(
    coffeewheelOutput('coffeewheel', width=400, height=400)
  )
)),

shinyServer(function(input, output){
 output$coffeewheel <- renderCoffeewheel({

   coffeewheel(sampleWheelData, width=500, height=500, main="Sample Wheel Title", partitionAttribute="value")

 })

})
)

**Comment by armish** [comment]
Hi Karim,

Sorry that I wasn't able to get to this earlier as I was out of the office for the last few days. Can you give me an update on this? Were you able to resolve the issue on your own or do we need to fix in the repository.

Thanks!

**Comment by kmezhoud** [comment]
HI Arman,
Yes I resolved this issue ;), Thanks.
Know I am an other one less difficult.
Actually It is possible with my app to change the gene list and get  'Reatively' the coffeewheel of genetic profile from cgdsr server. BUT
If I change the gene list the second coffeewheel superimpose the first one. I need the delete the first one before to generate the second one.
I am learning about "Shiny.unbindAll"  but it does not work:  "could not find function "Shiny.unbindAll""....

Any suggestion to avoid superimposing  coffeewheels?

here the structure of the Render

  output$getCoffeeWheel_Met <- renderCoffeewheel({
    withProgress(message = 'Creating Wheel. Waiting...', value = 0.1, {
      Sys.sleep(0.25)

```
 ## this function load profiles data and list of data frame
  getListProfData()

## this function restructurate the list of dataframes a tree with setting colors
  CoffeewheelTreeMetData <- reStrDimension(r_data$ListMetData)
  #title<- paste("Methylations: HM450 and HM27")
  coffeewheel(CoffeewheelTreeMetData, width=600, height=600) # main=title
})
```

https://drive.google.com/file/d/0B9NOY9eukkEeTmRfZE5qdGVwaGM/view?usp=sharing

  })
